pgsql:
  url: jdbc:postgresql://localhost:5432/bookshelf_service
  username: postgres
  password: 177013

jwt:
  secret: 7nFXppcVmvNxL6YJsbFmSPLDodpXu99ymCTBDHFhs6t33gzkXUwJkoI2WhpEzyO7
  access:
    lifetime: 6000000
  refresh:
    lifetime: 2592000
