pgsql:
  url: jdbc:postgresql://localhost:5432/bookshelf_service
  username: postgres
  password: 177013

spring:
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      password: 177013
      port: 6379
